### DISCUSSION TITLE
How to configure the download path?

### DISCUSSION THREAD

**Discussion by gNeeUs** [jcwillox/hass-auto-backup#117] [Q&A]
Thanks for providing this very nice Auto Backup integration!

I have trouble understanding how to configure the download path. Obviously there is an error because the automation that should run the local backup is failing. I simply do not know how to write the syntax for the desired download path.

In the UI at Settings > System > Storage, I have successfully configured Network storage with the Samba/Windows (CIFS) protocol to a share on my NAS on the LAN. Home Assistant runs on a Windows computer on my LAN, inside an Oracle VirtualBox VM.

The YAML of my current automation is copied below. Thanks for any assistance!

```
alias: Backup Full daily
description: created with Auto Backup integration
trigger:
  - platform: time
    at: "03:01:00"
condition: []
action:
  - service: auto_backup.backup_full
    data:
      compressed: true
      keep_days: 7
      download_path:
        - \\nas01\Backup_share\ha_folder
mode: single
```
