### DISCUSSION TITLE
Is there a way to exclude the HA database?

### DISCUSSION THREAD

**Discussion by Duke-Box** [jcwillox/hass-auto-backup#189] [Q&A] [answered]
I notice that using the native ```action: hassio.backup_full``` there is an option to exclude the HA database.

e.g
```
action: hassio.backup_full
data:
  compressed: true
  homeassistant_exclude_database: true
  location: Office_laptop_Hassio_backups
  name: Full backup {{ now().strftime('%Y-%m-%d %H:%M') }}
```

Is this possible with this integration? Or if not, can it be added to the exclusions?
