### DISCUSSION TITLE
Backup is now stored locally and on NAS.

### DISCUSSION THREAD

**Discussion by XVBinh** [jcwillox/hass-auto-backup#95] [Q&A] [answered]
Hello, 
I want to store the backups only on the NAS. Now does it also store it locally.  This is how the code looks like. 

```
alias: auto backup
description: ""
trigger:
  - platform: time
    at: "02:30:00"
condition:
  - condition: time
    weekday:
      - sun
      - fri
      - wed
      - mon
action:
  - service: auto_backup.backup_full
    data:
      name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
      keep_days: 7
      download_path: /media/nasbinh/Back-ups/
mode: single
```
Now does he store it locally in the normal HA back-ups folder and on the NAS. Is there a way to not have the back-up locally?
