### ISSUE TITLE
_mkdir_and_generate_backup_contents

### ISSUE THREAD

**Issue by DarthSonic** [jcwillox/hass-auto-backup#101]
### The problem

Auto Backup always return "_mkdir_and_generate_backup_contents" by fail event. How to fix that on synology NAS with Home assistant core installed? Manual backup works.

Logger: custom_components.auto_backup
Source: custom_components/auto_backup/__init__.py:187
Integration: Auto Backup (documentation, issues)
First occurred: 16:46:17 (1 occurrences)
Last logged: 16:46:17

Error during backup. Unable to patch '_mkdir_and_generate_backup_contents' function 

### What version of Auto Backup has the issue?

1.3.2

### What version of Home Assistant are you running?

2003.1.7

### What type of installation are you running?

Home Assistant Core

**Comment by zeHamish** [comment]
+1 - been happening for a week or so - just starting to get to look at it today

Home Assistant 2023.1.2 CORE
Frontend 20230104.0 - latest
DOCKER installation

HOST: rPi3B+
Linux Maschinenmensch 5.15.76-v8+ #1597 SMP PREEMPT Fri Nov 4 12:16:41 GMT 2022 aarch64 GNU/Linux
29GB free, backups are single digit storage usage - m.2 SSD

AutoBackup version: 1.3.2
no customisations to integration or automation. installed strictly base as per online process

**Comment by Robert-Zacchigna** [comment]
This error also just happened to me last night after updating the integration to the latest version (1.3.0 -> 1.3.2), i do have an automation setup using it but i have not experienced this error before today after updating.

Error:
```
2023-04-25 00:00:00.154 ERROR (MainThread) [custom_components.auto_backup] Error during backup. Unable to patch '_mkdir_and_generate_backup_contents' function.
```

Automation:
```yaml
alias: Automatic Backups
description: ''
use_blueprint:
  path: jcwillox/automatic_backups.yaml
  input:
    backup_time: 00:00:00
    use_action_hourly: true
    enable_yearly: true
    backup_action:
    - service: auto_backup.backup
      data:
        name: '{{ name }}'
        password: '{{ password }}'
        keep_days: '{{ keep_days }}'
        include_folders:
        - config
    condition: []
    enable_monthly: true
```
