### ISSUE TITLE
Backup failed triggered, but its not

### ISSUE THREAD

**Issue by KimCarlsen** [jcwillox/hass-auto-backup#107]
### The problem

I get the following error every day:         
"Timeout on /backups/new/full request. There may be a backup already in  progress."

But the backup seems to have completed.

### What version of Auto Backup has the issue?

1.3.2

### What version of Home Assistant are you running?

2023.7.1

### What type of installation are you running?

Home Assistant Supervised

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2023.7.1

### Example YAML snippet

```yml
alias: Automatic Backups
description: ""
use_blueprint:
  path: jcwillox/automatic_backups.yaml
  input:
    backup_time: "23:00:00"
    enable_monthly: false
    enable_yearly: false
    keep_days: 7


alias: Notify - Auto Backup failed
description: ""
use_blueprint:
  path: jcwillox/notify_auto_backup.yaml
  input:
    devices:
      - 0c4f0dc4ba605aa215898115abdcc1d8
    only_after: "06:00:00"
```
