### ISSUE TITLE
Doubled automation for hass-auto-backup can not be purged

### ISSUE THREAD

**Issue by michael5411** [jcwillox/hass-auto-backup#113]
### The problem

I’m using all the latest and up-to-date versions of HA, HACS and today I updated hass-auto-backup. It’s checked and OK.

BEFORE building a new backup automation in HA,  I realized, that there where TWO automations of my backup-script named:  "Backup täglich HACS“. I never built two of them.

When trying to open the first of these scripts, there came a message: „… can only be edited in YAML“. But there is no accessible YAML. At the entity-menu I get the info, that there is no unique entity-ID for it .. etc.

As a result I have an automation, that is running fine „Backup täglich HACS_neu“ and an 2nd automation, that is **NOT part of automation.YAML** and therefore, it is by no means (that are familiar to me) possible to delete it. I’ve deactivated it. 

But: HOW DO I DELETE IT?

Looks for me like the „header of the automation“ was separated from the YAML - possibly when updating hass-auto-backup - and now I’ve no access to the header and therefore I got „a dead lame duck“ of an automation header without context.

Here is the YAML of my (working) automation. It is exactly the same YAML, that was used for the no erasable automation (the alias is slightly different):

```
alias: Backup täglich HACS_neu
description: ""
trigger:
  - platform: time
    at: "01:55:00"
condition: []
action:
  - service: auto_backup.backup_full
    data:
      name: Auto Backup HACS
      keep_days: 3
mode: single
```

### What version of Auto Backup has the issue?

lastest update

### What version of Home Assistant are you running?

lastest

### What type of installation are you running?

Home Assistant Container

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

lastest

### Example YAML snippet

```yml
alias: Backup täglich HACS_neu
description: ""
trigger:
  - platform: time
    at: "01:55:00"
condition: []
action:
  - service: auto_backup.backup_full
    data:
      name: Auto Backup HACS
      keep_days: 3
mode: single
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
