### ISSUE TITLE
download_path not working when using blueprint

### ISSUE THREAD

**Issue by jimkerry01GH** [jcwillox/hass-auto-backup#118]
### The problem

I was also unable to get the download_path option to work.

Used the provided Blueprint.
Added download_path to my Automation that used the Blueprint.
Was unable to get download_path to work.

Checked the Trace output when using the Blueprint and download_path was not there.
Created my own Automation that did *not* use the Blueprint and download_path worked the first time.

### What version of Auto Backup has the issue?

v1.4.1

### What version of Home Assistant are you running?

Home Assistant 2023.10.5

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Supervisor 2023.10.1

### Example YAML snippet

```yml
alias: Auto Backup
description: ""
use_blueprint:
  path: jcwillox/automatic_backups.yaml
  input:
    download_path: /share/testShare/HA_Backup
    enable_daily: false
```
