### ISSUE TITLE
Backups not being renamed

### ISSUE THREAD

**Issue by sxdjt** [jcwillox/hass-auto-backup#123]
### The problem

I have the following to run daily full backups, which work except that the backup filename is the temp file name (e.g. "5e2c6169.tar").  Shouldn't the backup be renamed as specified?

### What version of Auto Backup has the issue?

1.4.1

### What version of Home Assistant are you running?

2024.1.5

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2023.12.1

### Example YAML snippet

```yml
alias: Daily Full Backup
description: ""
trigger:
  - platform: time_pattern
    hours: "1"
action:
  - service: auto_backup.backup_full
    data:
      compressed: true
      keep_days: 7
      name: "HA Backup {{ now().strftime('+%d-%b-%y') }}"
mode: single
```
```


### Anything in the logs that might be useful for us?

_No response_

### Additional information

_No response_
