### ISSUE TITLE
Full Backup with Excluded Folders is handled as Partial Backup

### ISSUE THREAD

**Issue by dafunkydan** [jcwillox/hass-auto-backup#127]
### The problem

According to the Docs, it is possible to perform a Full Backup with exclude.
However, when trying to restore a Full Backup with such an exclude (in my Case: Folder 'Share'), the Dialog is for "Partial Restore".
What i expect for a Full Backup is the Dialog for "Do you want to completely wipe your System and Restore the Backup".

### What version of Auto Backup has the issue?

1.4.1

### What version of Home Assistant are you running?

2024.02.05

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2024.02.1

### Example YAML snippet

```yml
service: auto_backup.backup_full
data:
  name: FullBackup {{ now().strftime('%Y-%m-%d %H-%M') }}
  keep_days: 7
  download_path: /media/FritzNas_Mounted/Homeassistant_Backups/
  exclude:
    folders:
      - share
```

### Additional information

Edit: 
While comparing the created Backups inside, i noticed for such a Full Backup with Excludes, in backup.json it is written ""FullBackup 2024-03-02 11-23","date":"2024-03-02T10:23:16.371324+00:00","type":"partial", - while the same Service Call, but without Excludes, saves the type as full.
Furthermore, the Structure inside the Tar differs:
- A 'true' Full Backup has the Structure \.\*.tar.gz, and the backup.json sitting inside, along with the tar.gz.
- A Full Backup with excludes has the Structure  \*.tar.gz, the only subfolder beeing \.\, with only the backup.json inside.
