### ISSUE TITLE
why do backup files keep getting bigger?

### ISSUE THREAD

**Issue by harry7474** [jcwillox/hass-auto-backup#146]
### The problem

when i started using autobackup, the backup files were about 100 MB in size. by now they have blown up to more than 600 MB, taking up A LOT of space on my NAS.

### What version of Auto Backup has the issue?

1.5.0

### What version of Home Assistant are you running?

2024.6.3

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2024.06.0

### Example YAML snippet

```yml
service: auto_backup.backup_full
data:
  compressed: true
  keep_days: 15
```
