### ISSUE TITLE
Folder include      /addon_configs

### ISSUE THREAD

**Issue by pfeifferch** [jcwillox/hass-auto-backup#149]
### The problem

When I create a partial backup, I can easily add the following folders:

  folders:
    - addons
    - config
    - share
    - ssl

However, if I add the following entry, the backup fails
    - addon_configs
However, the folder exists and also has a subfolder with a configuration file for Traccar. 

AB 
  v 1.5.0

HA 
  Core
    2024.7.2
  Supervisor
    2024.06.2
  Operating System
    12.3
  Frontend
    20240710.0

### What version of Auto Backup has the issue?

1.5.0

### What version of Home Assistant are you running?

20240702

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

20240602

### Example YAML snippet

```yml
service: auto_backup.backup_partial
data:
  compressed: true
  addons:
    - "*"
  folders:
    - addons
    - config
    - share
    - ssl
  keep_days: 7
  name: Auto-Backup -taeglich partiell- {{ now().strftime('%Y-%m-%d %H-Uhr-%M')}}





service: auto_backup.backup_partial
data:
  compressed: true
  addons:
    - "*"
  folders:
    - addons
    - addon_configs
    - config
    - share
    - ssl
  keep_days: 7
  name: Auto-Backup -taeglich partiell- {{ now().strftime('%Y-%m-%d %H-Uhr-%M')}}
```
