### ISSUE TITLE
Backup fails with "Error during backup. [Errno 122] Quota exceeded"

### ISSUE THREAD

**Issue by weberruss** [jcwillox/hass-auto-backup#150]
### The problem

I am using the automation blueprint, but no backups are created. 
```
alias: Automatic Backups
description: ""
use_blueprint:
  path: jcwillox/automatic_backups.yaml
  input:
    enable_yearly: false

```

All I get is the following error message in the log:

```
2024-07-19 02:30:05.965 ERROR (MainThread) [custom_components.auto_backup] Error during backup. [Errno 122] Quota exceeded
```

### What version of Auto Backup has the issue?

V1.5.0

### What version of Home Assistant are you running?

2024.7.2

### What type of installation are you running?

Home Assistant Container
