### ISSUE TITLE
Error: Backup in Progress?

### ISSUE THREAD

**Issue by RoadkillUK** [jcwillox/hass-auto-backup#16]
2020-05-02 04:30:02 ERROR (MainThread) [custom_components.auto_backup] Error during backup. There may be a backup already in progress.

I know this isn't much info, please let me know what you need.

Also, it used to work.

```
snapshot_backup:
  alias: Shapshot Backup
  sequence:
  - service: auto_backup.snapshot_partial
    data_template:
      name: Automated Backup {{ now().strftime('%d/%m/%Y/%a') }}
      addons:
        - ae6e943c_custom_deps
        - core_check_config
        - a0d7b954_grafana
        - core_samba
        - 15ef4d2f_esphome-beta
        - core_ssh
        - 3833edd4_googlebackup
      folders:
        - homeassistant
        - share
        - ssl
        - local
      keep_days: 7

```

HASSIO  0.109.0
Pi4
