### ISSUE TITLE
AutoBackup not encrypting with 2025.1 backup enhancements

### ISSUE THREAD

**Issue by blacknell** [jcwillox/hass-auto-backup#180]
### The problem

I would expect this addon to be transparently taking advantage of the new encryption in 2025.1 backups

### What version of Auto Backup has the issue?

1.5.3

### What version of Home Assistant are you running?

2025.1.0

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

2024.12.3

### Additional information

I generated backups from an automation using
```yaml
actions:
  - data:
      name: "{{ now().strftime('%Y%m%d-%H%M%S%z') }}-sandalwood-full-daily"
      keep_days: 7
    action: auto_backup.backup_FULL
```

When I download the zip file the contents are as before - unencrypted

**Comment by jcwillox** [comment]
Backups from this service probably won't ever be encrypted by default, as that'd be a breaking change, however, they have always supported encryption by adding the `password` option, so encrypted backup are still very much working and supported.

```yaml
action: auto_backup.backup
target: {}
data:
  name: Test Backup 2
  keep_days: 0.0001
  password: "1234"
  include_folders:
    - config
```

Of course you are talking about home assistant's new encrypted by default backups with their dedicated encryption key and recovery file. I don't know whether that can be supported but from what it seems it should be possible, and I would likely add a new paramater to the service `encrypted: true`. Would you mind create a feature request ticket for this?
