### ISSUE TITLE
[FR]: Support for 2025.1 native encryption in backups

### ISSUE THREAD

**Issue by blacknell** [jcwillox/hass-auto-backup#181]
### Is your feature request related to a problem? Please describe.

The native encryption introduced in 2025.1 is very useful but this addon doesn't take advantage of it.
Relates #180 

### Describe the solution you'd like

Add a configuration parameter (default false) to use the encryption provided in core
```
encryption: true
```
It would need to be mutually exclusive with `password` option

### Describe alternatives you've considered

Use the addon password option but this FR has the advantage of using the core extensions eg recovery file

**Comment by jcwillox** [comment]
Ok so just checked out how home assistant does their native encryptions and they literally just set the password on the backup to that key, the `AAAA-BBBB-CCCC-DDDD-EEEE-FFFF-GGGG` key they show you when you first create a backup now.

So its as easy as just this
```yaml
action: auto_backup.backup
target: {}
data:
  name: Hello World
  password: "AAAA-BBBB-CCCC-DDDD-EEEE-FFFF-GGGG" # add your encryption key here
  keep_days: 3
```

That said I'll try add a shortcut that'll automatically set the password to your secret key, I just have to figure out how to get your current secret key.
