### ISSUE TITLE
Unable to extract homeassistant.tar.gz from backup

### ISSUE THREAD

**Issue by Aad3229** [jcwillox/hass-auto-backup#190]
### The problem

I installed auto-backup and scheduled my first backup with the option "Encryped" off. It runs OK and the file 07b57f35.tar is made in the /config/backups directory. If I unpack this file, I get a directory with the files backup.json and homeassistant.tar.gz. If I try to unpack this last file I get an error:
"the archive is either in unknown format or damaged" 

### What version of Auto Backup has the issue?

1.7.0

### What version of Home Assistant are you running?

2025.1.3

### What type of installation are you running?

Home Assistant Container

### Example YAML snippet

```yml
- id: '1737467250131'
  alias: AutoBackup1
  description: ''
  use_blueprint:
    path: jcwillox/automatic_backups.yaml
    input:
      backup_time: '15:40:00'
      encrypted: false
```

### Anything in the logs that might be useful for us?

```python3
nothing in the logs
```
