### ISSUE TITLE
Question: 0.7.0 Advanced configuration.

### ISSUE THREAD

**Issue by niemyjski** [jcwillox/hass-auto-backup#28]
From the change log it says yaml configuration has been migrated but what about advanced configuration like folder excludes? Are these still configured properly if I remove my yaml? How do I update it?

**Comment by jcwillox** [comment]
If you're talking about service calls/automations, then no, nothing has changed.

"yaml configuration" refers to the `auto_backup` entry in your configuration.yaml file, which is the options for Auto Backup itself. I probably could've been clearer, but what I meant is you can now setup Auto Backup using the UI configuration method, just like how you would've setup HACS, e.g. `Configuration` -> `Integrations` -> `Add Integrations` -> `Search for Auto Backup` -> `Submit`. 

However, if you were already are running Auto Backup, then after updating your YAML configuration is read and used to create a configuration entry in the UI, at which point the YAML config is will no longer do anything, any further configuration is done using the UI, e.g.  `Configuration` -> `Integrations` -> `Auto Backup` -> `Options`.

For example, if this was your YAML configuration it can be removed after updating.
```yaml
# Example configuration.yaml entry
auto_backup:
  auto_purge: true
  backup_timeout: 1200
```

Hopefully, that clears things up?

**Comment by niemyjski** [comment]
I have this in my config:

```yaml
auto_purge: true
exclude:
  folders:
    - /media/frigate
    - /media/mail
```

I was wondering about everything not listed above in your sample. The release notes made it sound like everything was imported and we needed to remove any config. Do I still need this config to augment the integration?
