### ISSUE TITLE
Folder are not included when running auto_backup.snapshot_full

### ISSUE THREAD

**Issue by cdrfun** [jcwillox/hass-auto-backup#5]
Hi there, first of all thanks for this great Integration. I have a small issue though: when using the following configuration, there are no folders in my backup file. 

```
- id: '1559941440463'
  alias: Perform Daily Backup
  trigger:
    platform: time
    at: "02:30:00"
  action:
    service: auto_backup.snapshot_full
    data_template:
      name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
      keep_days: 7
      password: !secret backup_password
      exclude:
        addons:
          - Syncthing
```

Maybe I'm missing something, but I think all folders should be backed up as well.
