### ISSUE TITLE
Partitial Maria DB Backup failed with Supervisor 2022.02.0

### ISSUE THREAD

**Issue by LuckyTriple7** [jcwillox/hass-auto-backup#50]
HA 2022.3.0b5
Supervisor 2022.02.0

```
service: auto_backup.backup_partial
data:
  addons:
    - core_mariadb
  name: 'Maria DB Backup: {{ now().strftime(''%A, %B %-d, %Y'') }}'
```

Supervisor Log:

```
22-03-01 18:29:26 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug bfc0c729
22-03-01 18:29:26 INFO (MainThread) [supervisor.backups.manager] Backing up bfc0c729 store Add-ons
22-03-01 18:29:27 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_mariadb
22-03-01 18:39:53 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_mariadb
22-03-01 18:39:53 INFO (MainThread) [supervisor.homeassistant.module] Backing up Home Assistant Core config folder
22-03-01 18:40:46 INFO (MainThread) [supervisor.homeassistant.module] Backup Home Assistant Core config folder done
22-03-01 18:40:47 ERROR (MainThread) [supervisor.backups.manager] Backup bfc0c729 error
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/backups/manager.py", line 152, in _do_backup
    folder_list.remove(FOLDER_HOMEASSISTANT)
ValueError: list.remove(x): x not in list
```

Manual Supervisor backup works.

There is a breaking change:

https://github.com/home-assistant/supervisor/pull/3451 New Backup format for core @pvizeli
