### ISSUE TITLE
Backups are not getting purged

### ISSUE THREAD

**Issue by Alex-joomla** [jcwillox/hass-auto-backup#55]
Hi guys. I guess i have a configuration problem with this component. 
Automation looks like this:
```yaml
- alias: Perform Daily Backup
  trigger:
    platform: time
    at: "02:30:00"
  condition:
    condition: time # Perform backup every day except Mondays.
    weekday:
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
  action:
    service: auto_backup.backup_full
    data:
      name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
      keep_days: 7
```

But Backups are not getting purged. (i have a purge action once a day too) Read in other issues, that this can be due to a timeout, since the monitored Backup counter is 0 and one Backup lasts about 3 hours. Activated the logger this way but getting way too less messages

```yaml
logger:
  default: warning
  logs:
    custom_components.auto_backup: debug
```

This is the output in logs:
![Bildschirmfoto 2022-04-28 um 16 23 12](https://user-images.githubusercontent.com/32268233/165774611-1131be86-8661-423e-979f-f3b4d42b5d5b.png)
