### ISSUE TITLE
Backup stops after folder exclusion

### ISSUE THREAD

**Issue by arjen-w** [jcwillox/hass-auto-backup#63]
After upgrading to HA version 2022.7.0 my backups are incomplete.
It seems like the job does not include any add-ons when a folder exclusion is  configured.

My task config:

```yaml
service: auto_backup.backup_full
data:
  name: 'DailyBackup: {{ now().strftime(''%A, %B %-d, %Y'') }}'
  keep_days: 2
  exclude:
    folders:
      - share
```

This always worked fine until the upgrade of HA.
A task without the excluded folder is working fine though, but as my share folder contains video recordings that I don't need to be backed-up, I want to exclude that folder.

The supervisor logs does not show any error.
