### ISSUE TITLE
Large backups due to big .git folder

### ISSUE THREAD

**Issue by davidw3591** [jcwillox/hass-auto-backup#69]
Hi,

My partial backups are quite large due to a large git pack file (.git\objects\pack\pack-xxxxxxxxx.pack 230MB). Would it be possible to exclude this somehow when running a partial backup?

My config:
```
automation:
  - alias: System - Backup - Config only every 2 hours
    trigger:
      # Perform backup every x hours
      platform: time_pattern
      hours: "/2"
    action:
      # Only perform a partial backup to save storage
      service: auto_backup.backup_partial
      data:
        name: "Config backup: {{ now().strftime('%H:%M %d/%m/%Y') }}"
        folders:
          - homeassistant
          # - share
          # - ssl
        keep_days: 3
```
