### ISSUE TITLE
auto_backup services missing in 2022.9.1

### ISSUE THREAD

**Issue by buffcode** [jcwillox/hass-auto-backup#71]
### The problem

After installation of the integration on 2022.9.1 the `auto_backup.*` services are not listed and my automations also fail to call them.

I re-downloaded the integration via HACS and restarted the system without any success.

The systemlog is not showing any error, despite the usual `We found a custom integration auto_backup which has not been tested by Home Assistant.`

### What version of Auto Backup has the issue?

1.3.0

### What version of Home Assistant are you running?

2022.9.1

### What type of installation are you running?

Home Assistant OS

### Example YAML snippet

```yml
# automation
alias: "Backup: täglich"
trigger:
  - platform: time
    at: "02:30"
condition:
  - condition: time
    weekday:
      - tue
      - wed
      - thu
      - fri
      - sat
      - sun
action:
  - service: auto_backup.backup_full
    data:
      name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
      keep_days: 7


----

# configuration.yml
logger:
    default: warning
    logs:
        custom_components.auto_backup: debug
```

### Anything in the logs that might be useful for us?

```python3
No log output despite debug is enabled.
```
