### ISSUE TITLE
Hourly backup isn't actually hourly

### ISSUE THREAD

**Issue by genebean** [jcwillox/hass-auto-backup#80]
### The problem

The trigger for the hourly backup is 

```yaml
  - id: hourly
    enabled: true
    platform: time_pattern
    hours: /3
```

That does not have the hourly backup run each hour... I think that actually translates to every 8 hours

### What version of Auto Backup has the issue?

1.3.0

### What version of Home Assistant are you running?

Home Assistant 2022.12.4

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Supervisor 2022.11.2
