### ISSUE TITLE
Auto purge not working on expired backups

### ISSUE THREAD

**Issue by kaizersoje** [jcwillox/hass-auto-backup#9]
I have set auto_purge to true. However, I have noticed that expired backups are not getting automatically purged. Not sure what's wrong.

**Comment by jcwillox** [comment]
Likely, the backups are not being monitored for deletion. Backups will only be monitored if you set the `keep_days` parameter to a value > 0 in the service call. You can check if any backups are being monitored using either the sensor [`sensor.auto_backup`](https://github.com/jcwillox/hass-auto-backup#sensor) which will show the number of monitored backups or by looking at the file `/config/.storage/auto_backup.snapshots_expiry`

Also, keep in mind that setting `auto_purge` to true doesn't mean expired backups are remove immediately when they expire, they will only be removed (purged) when creating a new backup via a service call to `auto_backup` (i.e not through the web UI). They will also be purged when calling the `auto_backup.purge` service.

**Comment by kaizersoje** [comment]
I have set the `keep_days` parameter in my automations. I checked out the sensor `sensor.auto_backup` and found that `monitored_snapshots` is 0 and `purgeable_snapshots` is 0. What's wrong?

**Comment by jcwillox** [comment]
Could you also provide a copy of the service call your making in your automation?

Can you call the service below from the Developer Tools > Services section.
```yaml
service: auto_backup.snapshot_partial
service_data:
  name: Test
  keep_days: 0.0014
```
After calling that service, check the sensor to see if `monitored_snapshots` has changed.

Also if you can provide the logs created when calling the service that would be great. To enable debug logging use the logger component. Below is an example to enable debug logging for auto_backup, you can just paste that into your configuration.yaml.
```yaml
logger:
  default: warning
  logs:
    custom_components.auto_backup: debug
```

**Comment by kaizersoje** [comment]
I have provided a copy of my service call below

```
service: auto_backup.snapshot_full
    data_template:
      name: "Full AutoBackup: {{ now().strftime('%a %d/%m/%y') }}"
      keep_days: 7
```

**Comment by kaizersoje** [comment]
I tried the service call below

```
service: auto_backup.snapshot_partial
service_data:
  name: Test
  keep_days: 0.0014
```
I can see that the `monitored_snapshots` is now showing 1

**Comment by kaizersoje** [comment]
`purgeable_snapshots` is showing up as 1 too

**Comment by jcwillox** [comment]
Well sounds like everything is working correctly, you can now either call `auto_backup.purge` to remove the expired backup, or when you create your next backup it will be removed.

There may just be an issue with your automations. Can you confirm that your automations are valid and are triggering correctly?

This is an example of a valid automation that you could put in your automations.yaml file. `keep_days` is set to 2 minutes to make testing easier.
```yaml
- alias: Perform Daily Backup
  trigger:
    platform: time
    at: "02:30:00"
  action:
    service: auto_backup.snapshot_full
    data_template:
      name: "DailyBackup: {{ now().strftime('%A, %B %-d, %Y') }}"
      keep_days: 0.0014
```

**Comment by kaizersoje** [comment]
My backups are triggering correctly. Below are the 2 automations I have

```
- alias: Perform Full Backup
  trigger:
    platform: time
    at: "01:30:00"
  condition:
    condition: time # Perform backup on Mondays.
    weekday:
      - mon
      - thu
  action:
    service: auto_backup.snapshot_full
    data_template:
      name: "Full AutoBackup: {{ now().strftime('%a %d/%m/%y') }}"
      keep_days: 7

- alias: Perform Partial Backup
  trigger:
    platform: time
    at: "01:30:00"
  condition:
    - condition: time
      weekday:
        - tue
        - wed
        - fri
        - sat
        - sun
  action:
    service: auto_backup.snapshot_partial 
    data_template:
      name: "Partial AutoBackup: {{ now().strftime('%a %d/%m/%y') }}"
      folders:
        - homeassistant
        - share
        - ssl
      keep_days: 2
```

**Comment by jcwillox** [comment]
Yep, those look fine, try manually triggering one of the automations from the web UI (wait for it to finish) and watch the Auto Backup sensor. 

Also, it doesn't look like your automations clash, so this shouldn't apply to your situation, but I still want to mention that Auto Backup can (currently) only perform one snapshot at a time, if you try to create another snapshot before the other one has finished, Hass.io may still create the second snapshot but it will not be monitored by Auto Backup.

**Comment by kaizersoje** [comment]
I manually triggered and the automation successfully ran and created the backup. However, `monitored_snapshots` is still showing up as 0.

**Comment by kaizersoje** [comment]
I saw this notification this morning

Snapshot Failed.
Name: Partial AutoBackup: Sat 14/03/20
Error: There may be a backup already in progress.

I am not sure how this is possible.

**Comment by jcwillox** [comment]
Yeah, I'm not sure either. That error means the request to the Hass.io API was successful, but the response from Hass.io was not valid, i.e it didn't contain the identifier for the snapshot. Hass.io may have created the backup but some error happened and it didn't give Auto Backup the ID.

Usually, this is caused when another backup is currently in progress, so naturally, make sure there are no other automations or addons that could be creating a backup at that time.

Did you just add that notification automation, or has that been present the whole time?

To help you any further I'm going to need those debug logs that I mentioned earlier, so I can properly see what's going on.

**Comment by kaizersoje** [comment]
I have attached the logs below from last night.

The backup `Full AutoBackup: Mon 16/03/20 ` was created successfully. However, I noticed this in my notifications too, which I think was created around 1.50AM.

```
Snapshot Failed.
Name: Full AutoBackup: Mon 16/03/20
Error:
```

```
2020-03-16 01:30:00 DEBUG (MainThread) [custom_components.auto_backup] Creating snapshot Full AutoBackup: Mon 16/03/20
2020-03-16 01:30:00 DEBUG (MainThread) [custom_components.auto_backup] New snapshot; command: /snapshots/new/full, keep_days: 7.0, data: {'name': 'Full AutoBackup: Mon 16/03/20'}, timeout: 1200
2020-03-16 01:50:00 ERROR (MainThread) [custom_components.auto_backup] Timeout on /snapshots/new/full request
2020-03-16 01:50:00 ERROR (MainThread) [custom_components.auto_backup] Error during backup. 
2020-03-16 01:50:00 DEBUG (MainThread) [custom_components.auto_backup] No snapshots required purging.
```

**Comment by jcwillox** [comment]
Thanks! This makes it a lot clearer.

The issue is due to a timeout error. Auto Backup waits by default 20 minutes for a snapshot to complete, if it takes longer than that, it is assumed the snapshot failed.

This is usually caused by taking large backups. There is a configuration option to increase this timeout `backup_timeout`. This is very likely the cause as Hass.io would still create the backup but it will not be monitored. _I was actually thinking yesterday that this may have been the issue _.

Try taking a manual full backup and timing how long it takes then add like 20 minutes.

```yaml
auto_backup:
  auto_purge: true
  backup_timeout: 2400  # 40 minutes, needs to be converted to seconds.
```
