### ISSUE TITLE
keep_days not work

### ISSUE THREAD

**Issue by poudenes** [jcwillox/hass-auto-backup#94]
### The problem

Created a automation and add the 'keep_days' but it seems that this is not doing the job

### What version of Auto Backup has the issue?

1.3.1

### What version of Home Assistant are you running?

Home Assistant 2023.3.6

### What type of installation are you running?

Home Assistant OS

### If you're running HA OS/Supervised, what version of the Supervisor are you running?

Supervisor 2023.03.2

### Example YAML snippet

```yml
- id: "c6f71eb7-e1ef-4f30-a6d9-0ab3594783eb"
  alias: "System - Partial Backup on rest of the week"

  trigger:
    - platform: time
      at: "09:30:00"

  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat

  action:
    - service: auto_backup.backup_partial
      data:
        name: "Partial Backup - {{ now().strftime('%Y-%m-%d') }}"
        folders:
          - config
        download_path: 
          - /share/backup/partial
        keep_days: 3

    - wait_template: "{{ states('sensor.processor_use')|int < 15}}"
    
    - service: persistent_notification.create
      data:
        title: "System - Automated backup done"
        message: "Home Assistant partial backup is created. {{ now().strftime('%F') }}"
        notification_id: "1"
```

```
➜  partial pwd
/share/backup/partial

➜  partial ls -al -t
total 1373896
-rw-r--r--    1 root     root     351733760 Mar 25 09:48 Partial_Backup_2023_03_25.tar
drwxr-xr-x    2 root     root          4096 Mar 25 09:48 .
-rw-r--r--    1 root     root     351744000 Mar 24 09:48 Partial_Backup_2023_03_24.tar
-rw-r--r--    1 root     root     351744000 Mar 23 09:48 Partial_Backup_2023_03_23.tar
-rw-r--r--    1 root     root     351621120 Mar 22 09:48 Partial_Backup_2023_03_22.tar
drwxr-xr-x    4 root     root          4096 Mar 11 09:07 ..
```
```

### Other information
In settings > system > backup there are only last 3 backups listed.
