### ISSUE TITLE
Backup fails with "unable to patch" message since HA 2023.4

### ISSUE THREAD

**Issue by danielzwink** [jcwillox/hass-auto-backup#97]
### The problem

Since I updated home assistant to version 2023.4.0 my backup fails consistently with message **Unable to patch 
'_generate_backup_contents' function** being sent via the **auto_backup.backup_failed** event. Same still applies after going to version 2023.4.1 for HA.

My automation to trigger the backup is the following yaml:

```
alias: "Automatisierung: Backup täglich um 03:00 Uhr"
mode: single
trigger:
  - platform: time
    at: "03:00:00"
action:
  - service: auto_backup.backup
    data:
      name: >-
        Backup vom {{ now().strftime('%Y-%m-%d um %H-%M-%S') }} in Version {{
        states('sensor.home_assistant_version_current') }}
      keep_days: 14
      download_path:
        - /share/home-assistant-backups
```

With previous versions of HA it worked perfectly fine.

### What version of Auto Backup has the issue?

1.3.1

### What version of Home Assistant are you running?

Home Assistant 2023.4.1

### What type of installation are you running?

Home Assistant Container
